# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_oauth2_authenticatable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bhbryant"]
  s.date = %q{2010-06-13}
  s.description = %q{Implements OAuth2 for Devise, specifically integrating with facebook Graph}
  s.email = %q{benjamin@bryantmarkowsky.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "devise_oauth2_authenticatable.gemspec",
     "lib/devise_oauth2_authenticatable.rb",
     "lib/devise_oauth2_authenticatable/locales/en.yml",
     "lib/devise_oauth2_authenticatable/rails.rb",
     "lib/devise_oauth2_authenticatable/model.rb",
     "lib/devise_oauth2_authenticatable/routes.rb",
     "lib/devise_oauth2_authenticatable/schema.rb",
     "lib/devise_oauth2_authenticatable/strategy.rb",
     "lib/devise_oauth2_authenticatable/view_helpers.rb",
     "lib/generators/devise/oauth2_authenticatable/oauth2_authenticatable_generator.rb",
     "lib/generators/devise/oauth2_authenticatable/templates/oauth2_config.yml",
     "lib/generators/devise/oauth2_authenticatable/USAGE",
     "spec/devise_oauth2_authenticatable_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bhbryant/devise_oauth2_authenticatable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Implements OAuth2 for Devise}
  s.test_files = [
    "spec/devise_oauth2_authenticatable_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<devise>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<oauth2>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<devise>, [">= 1.0.0"])
      s.add_dependency(%q<oauth2>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<devise>, [">= 1.0.0"])
    s.add_dependency(%q<oauth2>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

